INSERT INTO `countries` (`id`, `value`) VALUES (1, 'Afghanistan');
INSERT INTO `countries` (`id`, `value`) VALUES (2, 'Aringland Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (3, 'Albania');
INSERT INTO `countries` (`id`, `value`) VALUES (4, 'Algeria');
INSERT INTO `countries` (`id`, `value`) VALUES (5, 'American Samoa');
INSERT INTO `countries` (`id`, `value`) VALUES (6, 'Andorra');
INSERT INTO `countries` (`id`, `value`) VALUES (7, 'Angola');
INSERT INTO `countries` (`id`, `value`) VALUES (8, 'Anguilla');
INSERT INTO `countries` (`id`, `value`) VALUES (9, 'Antarctica');
INSERT INTO `countries` (`id`, `value`) VALUES (10, 'Antigua and Barbuda');
INSERT INTO `countries` (`id`, `value`) VALUES (11, 'Argentina');
INSERT INTO `countries` (`id`, `value`) VALUES (12, 'Armenia');
INSERT INTO `countries` (`id`, `value`) VALUES (13, 'Aruba');
INSERT INTO `countries` (`id`, `value`) VALUES (14, 'Australia');
INSERT INTO `countries` (`id`, `value`) VALUES (15, 'Austria');
INSERT INTO `countries` (`id`, `value`) VALUES (16, 'Azerbaijan');
INSERT INTO `countries` (`id`, `value`) VALUES (17, 'Bahamas');
INSERT INTO `countries` (`id`, `value`) VALUES (18, 'Bahrain');
INSERT INTO `countries` (`id`, `value`) VALUES (19, 'Bangladesh');
INSERT INTO `countries` (`id`, `value`) VALUES (20, 'Barbados');
INSERT INTO `countries` (`id`, `value`) VALUES (21, 'Belarus');
INSERT INTO `countries` (`id`, `value`) VALUES (22, 'Belgium');
INSERT INTO `countries` (`id`, `value`) VALUES (23, 'Belize');
INSERT INTO `countries` (`id`, `value`) VALUES (24, 'Benin');
INSERT INTO `countries` (`id`, `value`) VALUES (25, 'Bermuda');
INSERT INTO `countries` (`id`, `value`) VALUES (26, 'Bhutan');
INSERT INTO `countries` (`id`, `value`) VALUES (27, 'Bolivia');
INSERT INTO `countries` (`id`, `value`) VALUES (28, 'Bosnia and Herzegovina');
INSERT INTO `countries` (`id`, `value`) VALUES (29, 'Botswana');
INSERT INTO `countries` (`id`, `value`) VALUES (30, 'Bouvet Island');
INSERT INTO `countries` (`id`, `value`) VALUES (31, 'Brazil');
INSERT INTO `countries` (`id`, `value`) VALUES (32, 'British Indian Ocean territory');
INSERT INTO `countries` (`id`, `value`) VALUES (33, 'Brunei Darussalam');
INSERT INTO `countries` (`id`, `value`) VALUES (34, 'Bulgaria');
INSERT INTO `countries` (`id`, `value`) VALUES (35, 'Burkina Faso');
INSERT INTO `countries` (`id`, `value`) VALUES (36, 'Burundi');
INSERT INTO `countries` (`id`, `value`) VALUES (37, 'Cambodia');
INSERT INTO `countries` (`id`, `value`) VALUES (38, 'Cameroon');
INSERT INTO `countries` (`id`, `value`) VALUES (39, 'Canada');
INSERT INTO `countries` (`id`, `value`) VALUES (40, 'Cape Verde');
INSERT INTO `countries` (`id`, `value`) VALUES (41, 'Cayman Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (42, 'Central African Republic');
INSERT INTO `countries` (`id`, `value`) VALUES (43, 'Chad');
INSERT INTO `countries` (`id`, `value`) VALUES (44, 'Chile');
INSERT INTO `countries` (`id`, `value`) VALUES (45, 'China');
INSERT INTO `countries` (`id`, `value`) VALUES (46, 'Christmas Island');
INSERT INTO `countries` (`id`, `value`) VALUES (47, 'Cocos (Keeling) Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (48, 'Colombia');
INSERT INTO `countries` (`id`, `value`) VALUES (49, 'Comoros');
INSERT INTO `countries` (`id`, `value`) VALUES (50, 'Congo');
INSERT INTO `countries` (`id`, `value`) VALUES (51, 'Congo');
INSERT INTO `countries` (`id`, `value`) VALUES (52, ' Democratic Republic');
INSERT INTO `countries` (`id`, `value`) VALUES (53, 'Cook Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (54, 'Costa Rica');
INSERT INTO `countries` (`id`, `value`) VALUES (55, 'Ivory Coast (Ivory Coast)');
INSERT INTO `countries` (`id`, `value`) VALUES (56, 'Croatia (Hrvatska)');
INSERT INTO `countries` (`id`, `value`) VALUES (57, 'Cuba');
INSERT INTO `countries` (`id`, `value`) VALUES (58, 'Cyprus');
INSERT INTO `countries` (`id`, `value`) VALUES (59, 'Czech Republic');
INSERT INTO `countries` (`id`, `value`) VALUES (60, 'Denmark');
INSERT INTO `countries` (`id`, `value`) VALUES (61, 'Djibouti');
INSERT INTO `countries` (`id`, `value`) VALUES (62, 'Dominica');
INSERT INTO `countries` (`id`, `value`) VALUES (63, 'Dominican Republic');
INSERT INTO `countries` (`id`, `value`) VALUES (64, 'East Timor');
INSERT INTO `countries` (`id`, `value`) VALUES (65, 'Ecuador');
INSERT INTO `countries` (`id`, `value`) VALUES (66, 'Egypt');
INSERT INTO `countries` (`id`, `value`) VALUES (67, 'El Salvador');
INSERT INTO `countries` (`id`, `value`) VALUES (68, 'Equatorial Guinea');
INSERT INTO `countries` (`id`, `value`) VALUES (69, 'Eritrea');
INSERT INTO `countries` (`id`, `value`) VALUES (70, 'Estonia');
INSERT INTO `countries` (`id`, `value`) VALUES (71, 'Ethiopia');
INSERT INTO `countries` (`id`, `value`) VALUES (72, 'Falkland Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (73, 'Faroe Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (74, 'Fiji');
INSERT INTO `countries` (`id`, `value`) VALUES (75, 'Finland');
INSERT INTO `countries` (`id`, `value`) VALUES (76, 'France');
INSERT INTO `countries` (`id`, `value`) VALUES (77, 'French Guiana');
INSERT INTO `countries` (`id`, `value`) VALUES (78, 'French Polynesia');
INSERT INTO `countries` (`id`, `value`) VALUES (79, 'French Southern Territories');
INSERT INTO `countries` (`id`, `value`) VALUES (80, 'Gabon');
INSERT INTO `countries` (`id`, `value`) VALUES (81, 'Gambia');
INSERT INTO `countries` (`id`, `value`) VALUES (82, 'Georgia');
INSERT INTO `countries` (`id`, `value`) VALUES (83, 'Germany');
INSERT INTO `countries` (`id`, `value`) VALUES (84, 'Ghana');
INSERT INTO `countries` (`id`, `value`) VALUES (85, 'Gibraltar');
INSERT INTO `countries` (`id`, `value`) VALUES (86, 'Greece');
INSERT INTO `countries` (`id`, `value`) VALUES (87, 'Greenland');
INSERT INTO `countries` (`id`, `value`) VALUES (88, 'Grenada');
INSERT INTO `countries` (`id`, `value`) VALUES (89, 'Guadeloupe');
INSERT INTO `countries` (`id`, `value`) VALUES (90, 'Guam');
INSERT INTO `countries` (`id`, `value`) VALUES (91, 'Guatemala');
INSERT INTO `countries` (`id`, `value`) VALUES (92, 'Guinea');
INSERT INTO `countries` (`id`, `value`) VALUES (93, 'Guinea-Bissau');
INSERT INTO `countries` (`id`, `value`) VALUES (94, 'Guyana');
INSERT INTO `countries` (`id`, `value`) VALUES (95, 'Haiti');
INSERT INTO `countries` (`id`, `value`) VALUES (96, 'Heard and McDonald Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (97, 'Honduras');
INSERT INTO `countries` (`id`, `value`) VALUES (98, 'Hong Kong');
INSERT INTO `countries` (`id`, `value`) VALUES (99, 'Hungary');
INSERT INTO `countries` (`id`, `value`) VALUES (100, 'Iceland');
INSERT INTO `countries` (`id`, `value`) VALUES (101, 'India');
INSERT INTO `countries` (`id`, `value`) VALUES (102, 'Indonesia');
INSERT INTO `countries` (`id`, `value`) VALUES (103, 'Iran');
INSERT INTO `countries` (`id`, `value`) VALUES (104, 'Iraq');
INSERT INTO `countries` (`id`, `value`) VALUES (105, 'Ireland');
INSERT INTO `countries` (`id`, `value`) VALUES (106, 'Israel');
INSERT INTO `countries` (`id`, `value`) VALUES (107, 'Italy');
INSERT INTO `countries` (`id`, `value`) VALUES (108, 'Jamaica');
INSERT INTO `countries` (`id`, `value`) VALUES (109, 'Japan');
INSERT INTO `countries` (`id`, `value`) VALUES (110, 'Jordan');
INSERT INTO `countries` (`id`, `value`) VALUES (111, 'Kazakhstan');
INSERT INTO `countries` (`id`, `value`) VALUES (112, 'Kenya');
INSERT INTO `countries` (`id`, `value`) VALUES (113, 'Kiribati');
INSERT INTO `countries` (`id`, `value`) VALUES (114, 'Korea (north)');
INSERT INTO `countries` (`id`, `value`) VALUES (115, 'Korea (south)');
INSERT INTO `countries` (`id`, `value`) VALUES (116, 'Kuwait');
INSERT INTO `countries` (`id`, `value`) VALUES (117, 'Kyrgyzstan');
INSERT INTO `countries` (`id`, `value`) VALUES (118, 'Lao People\'s Democratic Republic');
INSERT INTO `countries` (`id`, `value`) VALUES (119, 'Latvia');
INSERT INTO `countries` (`id`, `value`) VALUES (120, 'Lebanon');
INSERT INTO `countries` (`id`, `value`) VALUES (121, 'Lesotho');
INSERT INTO `countries` (`id`, `value`) VALUES (122, 'Liberia');
INSERT INTO `countries` (`id`, `value`) VALUES (123, 'Libyan Arab Jamahiriya');
INSERT INTO `countries` (`id`, `value`) VALUES (124, 'Liechtenstein');
INSERT INTO `countries` (`id`, `value`) VALUES (125, 'Lithuania');
INSERT INTO `countries` (`id`, `value`) VALUES (126, 'Luxembourg');
INSERT INTO `countries` (`id`, `value`) VALUES (127, 'Macao');
INSERT INTO `countries` (`id`, `value`) VALUES (128, 'Macedonia');
INSERT INTO `countries` (`id`, `value`) VALUES (129, 'Madagascar');
INSERT INTO `countries` (`id`, `value`) VALUES (130, 'Malawi');
INSERT INTO `countries` (`id`, `value`) VALUES (131, 'Malaysia');
INSERT INTO `countries` (`id`, `value`) VALUES (132, 'Maldives');
INSERT INTO `countries` (`id`, `value`) VALUES (133, 'Mali');
INSERT INTO `countries` (`id`, `value`) VALUES (134, 'Malta');
INSERT INTO `countries` (`id`, `value`) VALUES (135, 'Marshall Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (136, 'Martinique');
INSERT INTO `countries` (`id`, `value`) VALUES (137, 'Mauritania');
INSERT INTO `countries` (`id`, `value`) VALUES (138, 'Mauritius');
INSERT INTO `countries` (`id`, `value`) VALUES (139, 'Mayotte');
INSERT INTO `countries` (`id`, `value`) VALUES (140, 'Mexico');
INSERT INTO `countries` (`id`, `value`) VALUES (141, 'Micronesia');
INSERT INTO `countries` (`id`, `value`) VALUES (142, 'Moldova');
INSERT INTO `countries` (`id`, `value`) VALUES (143, 'Monaco');
INSERT INTO `countries` (`id`, `value`) VALUES (144, 'Mongolia');
INSERT INTO `countries` (`id`, `value`) VALUES (145, 'Montserrat');
INSERT INTO `countries` (`id`, `value`) VALUES (146, 'Morocco');
INSERT INTO `countries` (`id`, `value`) VALUES (147, 'Mozambique');
INSERT INTO `countries` (`id`, `value`) VALUES (148, 'Myanmar');
INSERT INTO `countries` (`id`, `value`) VALUES (149, 'Namibia');
INSERT INTO `countries` (`id`, `value`) VALUES (150, 'Nauru');
INSERT INTO `countries` (`id`, `value`) VALUES (151, 'Nepal');
INSERT INTO `countries` (`id`, `value`) VALUES (152, 'Netherlands');
INSERT INTO `countries` (`id`, `value`) VALUES (153, 'Netherlands Antilles');
INSERT INTO `countries` (`id`, `value`) VALUES (154, 'New Caledonia');
INSERT INTO `countries` (`id`, `value`) VALUES (155, 'New Zealand');
INSERT INTO `countries` (`id`, `value`) VALUES (156, 'Nicaragua');
INSERT INTO `countries` (`id`, `value`) VALUES (157, 'Niger');
INSERT INTO `countries` (`id`, `value`) VALUES (158, 'Nigeria');
INSERT INTO `countries` (`id`, `value`) VALUES (159, 'Niue');
INSERT INTO `countries` (`id`, `value`) VALUES (160, 'Norfolk Island');
INSERT INTO `countries` (`id`, `value`) VALUES (161, 'Northern Mariana Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (162, 'Norway');
INSERT INTO `countries` (`id`, `value`) VALUES (163, 'Oman');
INSERT INTO `countries` (`id`, `value`) VALUES (164, 'Pakistan');
INSERT INTO `countries` (`id`, `value`) VALUES (165, 'Palau');
INSERT INTO `countries` (`id`, `value`) VALUES (166, 'Palestinian Territories');
INSERT INTO `countries` (`id`, `value`) VALUES (167, 'Panama');
INSERT INTO `countries` (`id`, `value`) VALUES (168, 'Papua New Guinea');
INSERT INTO `countries` (`id`, `value`) VALUES (169, 'Paraguay');
INSERT INTO `countries` (`id`, `value`) VALUES (170, 'Peru');
INSERT INTO `countries` (`id`, `value`) VALUES (171, 'Philippines');
INSERT INTO `countries` (`id`, `value`) VALUES (172, 'Pitcairn');
INSERT INTO `countries` (`id`, `value`) VALUES (173, 'Poland');
INSERT INTO `countries` (`id`, `value`) VALUES (174, 'Portugal');
INSERT INTO `countries` (`id`, `value`) VALUES (175, 'Puerto Rico');
INSERT INTO `countries` (`id`, `value`) VALUES (176, 'Qatar');
INSERT INTO `countries` (`id`, `value`) VALUES (177, 'Runion');
INSERT INTO `countries` (`id`, `value`) VALUES (178, 'Romania');
INSERT INTO `countries` (`id`, `value`) VALUES (179, 'Russian Federation');
INSERT INTO `countries` (`id`, `value`) VALUES (180, 'Rwanda');
INSERT INTO `countries` (`id`, `value`) VALUES (181, 'Saint Helena');
INSERT INTO `countries` (`id`, `value`) VALUES (182, 'Saint Kitts and Nevis');
INSERT INTO `countries` (`id`, `value`) VALUES (183, 'Saint Lucia');
INSERT INTO `countries` (`id`, `value`) VALUES (184, 'Saint Pierre and Miquelon');
INSERT INTO `countries` (`id`, `value`) VALUES (185, 'Saint Vincent and the Grenadines');
INSERT INTO `countries` (`id`, `value`) VALUES (186, 'Samoa');
INSERT INTO `countries` (`id`, `value`) VALUES (187, 'San Marino');
INSERT INTO `countries` (`id`, `value`) VALUES (188, 'Sao Tome and Principe');
INSERT INTO `countries` (`id`, `value`) VALUES (189, 'Saudi Arabia');
INSERT INTO `countries` (`id`, `value`) VALUES (190, 'Senegal');
INSERT INTO `countries` (`id`, `value`) VALUES (191, 'Serbia and Montenegro');
INSERT INTO `countries` (`id`, `value`) VALUES (192, 'Seychelles');
INSERT INTO `countries` (`id`, `value`) VALUES (193, 'Sierra Leone');
INSERT INTO `countries` (`id`, `value`) VALUES (194, 'Singapore');
INSERT INTO `countries` (`id`, `value`) VALUES (195, 'Slovakia');
INSERT INTO `countries` (`id`, `value`) VALUES (196, 'Slovenia');
INSERT INTO `countries` (`id`, `value`) VALUES (197, 'Solomon Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (198, 'Somalia');
INSERT INTO `countries` (`id`, `value`) VALUES (199, 'South Africa');
INSERT INTO `countries` (`id`, `value`) VALUES (200, 'South Georgia and the South Sandwich Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (201, 'Spain');
INSERT INTO `countries` (`id`, `value`) VALUES (202, 'Sri Lanka');
INSERT INTO `countries` (`id`, `value`) VALUES (203, 'Sudan');
INSERT INTO `countries` (`id`, `value`) VALUES (204, 'Suriname');
INSERT INTO `countries` (`id`, `value`) VALUES (205, 'Svalbard and Jan Mayen Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (206, 'Swaziland');
INSERT INTO `countries` (`id`, `value`) VALUES (207, 'Sweden');
INSERT INTO `countries` (`id`, `value`) VALUES (208, 'Switzerland');
INSERT INTO `countries` (`id`, `value`) VALUES (209, 'Syria');
INSERT INTO `countries` (`id`, `value`) VALUES (210, 'Taiwan');
INSERT INTO `countries` (`id`, `value`) VALUES (211, 'Tajikistan');
INSERT INTO `countries` (`id`, `value`) VALUES (212, 'Tanzania');
INSERT INTO `countries` (`id`, `value`) VALUES (213, 'Thailand');
INSERT INTO `countries` (`id`, `value`) VALUES (214, 'Togo');
INSERT INTO `countries` (`id`, `value`) VALUES (215, 'Tokelau');
INSERT INTO `countries` (`id`, `value`) VALUES (216, 'Tonga');
INSERT INTO `countries` (`id`, `value`) VALUES (217, 'Trinidad and Tobago');
INSERT INTO `countries` (`id`, `value`) VALUES (218, 'Tunisia');
INSERT INTO `countries` (`id`, `value`) VALUES (219, 'Turkey');
INSERT INTO `countries` (`id`, `value`) VALUES (220, 'Turkmenistan');
INSERT INTO `countries` (`id`, `value`) VALUES (221, 'Turks and Caicos Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (222, 'Tuvalu');
INSERT INTO `countries` (`id`, `value`) VALUES (223, 'Uganda');
INSERT INTO `countries` (`id`, `value`) VALUES (224, 'Ukraine');
INSERT INTO `countries` (`id`, `value`) VALUES (225, 'United Arab Emirates');
INSERT INTO `countries` (`id`, `value`) VALUES (226, 'United Kingdom');
INSERT INTO `countries` (`id`, `value`) VALUES (227, 'United States of America');
INSERT INTO `countries` (`id`, `value`) VALUES (228, 'Uruguay');
INSERT INTO `countries` (`id`, `value`) VALUES (229, 'Uzbekistan');
INSERT INTO `countries` (`id`, `value`) VALUES (230, 'Vanuatu');
INSERT INTO `countries` (`id`, `value`) VALUES (231, 'Vatican City');
INSERT INTO `countries` (`id`, `value`) VALUES (232, 'Venezuela');
INSERT INTO `countries` (`id`, `value`) VALUES (233, 'Vietnam');
INSERT INTO `countries` (`id`, `value`) VALUES (234, 'Virgin Islands (British)');
INSERT INTO `countries` (`id`, `value`) VALUES (235, 'Virgin Islands (US)');
INSERT INTO `countries` (`id`, `value`) VALUES (236, 'Wallis and Futuna Islands');
INSERT INTO `countries` (`id`, `value`) VALUES (237, 'Western Sahara');
INSERT INTO `countries` (`id`, `value`) VALUES (238, 'Yemen');
INSERT INTO `countries` (`id`, `value`) VALUES (239, 'Zaire');
INSERT INTO `countries` (`id`, `value`) VALUES (240, 'Zambia');
INSERT INTO `countries` (`id`, `value`) VALUES (241, 'Zimbabwe');
