INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (37, 'pc', 'piece', 'pieces', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (39, 'length', 'length', 'lengths', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (40, 'meter', 'meter', 'meters', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (41, 'roll', 'roll', 'rolls', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (42, 'box', 'box', 'boxes', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (43, 'set', 'set', 'sets', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (44, 'kg', 'kilogram', 'kilograms', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (45, 'liter', 'liter', 'liters', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (46, 'lot', 'lot', 'lots', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (47, 'man hour', 'man hour', 'man hours', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (48, 'kwh', 'kilowatt-hour', 'kilowatt-hours', '', 'Y');
INSERT INTO `uoms` (`id`, `short`, `name`, `plural_name`, `address`, `active`) VALUES (49, 'ml', 'milliliter', 'milliliters', '', 'Y');
